import type { Point, Bounds, Dimensions, CanvasShape, TextZone, TextBlock, PreviewGeometry, ResizeHandle } from './canvas';
import type { HistoryAction, HistoryTransaction, HistoryStacks, WorkspaceSnapshot } from './history';
import type { MockupAssets } from './assets';
import type { Slide, Device, EditorSettings, Ornament, OrnamentKind, OrnamentPatch, ElementSelection } from './model';
export interface FrameSpec {
    label: string;
    description?: string;
    src: string;
    maskSrc: string;
    width: number;
    height: number;
    aspect: number;
    sizeScale?: number;
    physicalW?: number;
    physicalH?: number;
    screenW?: number;
    screenH?: number;
    screen: {
        x: number;
        y: number;
        w: number;
        h: number;
        r?: number;
    };
}
export interface EditorSnapshot {
    selection: ElementSelection;
    slide: Slide;
    slides: Slide[];
    device: Device;
    frameSpecs: Record<string, FrameSpec>;
    canUndo: boolean;
    canRedo: boolean;
    toast: string;
    exporting: boolean;
    zoomMode: string;
    zoomPercent: number;
    inline: InlineEdit | null;
    frameWidth: string;
    frameHeight: string;
}
export interface InlineEdit {
    type: 'headline' | 'subtitle';
    original: string;
    style: import('react').CSSProperties;
}
export interface EditorSession {
    presets: Record<string, {
        w: number;
        h: number;
        name: string;
    }>;
    defaults: EditorSettings;
    ornamentCounter: number;
    selectedOrnament: number | null;
    createOrnament: (kind: OrnamentKind, copy?: OrnamentPatch) => Ornament;
    frameCounter: number;
    slideCounter: number;
    state: Slide;
    slides: Slide[];
    $: any;
    slideHistoryById: Record<number, HistoryStacks<Slide>>;
    workspaceUndo: import("./history").HistoryEntry<WorkspaceSnapshot>[];
    workspaceRedo: import("./history").HistoryEntry<WorkspaceSnapshot>[];
    historySequence: number;
    historyTransaction: HistoryTransaction | null;
    inputHistoryTransaction: {
        slide: Slide;
        before: Slide;
    } | null;
    historyObjectIds: WeakMap<HTMLImageElement, number>;
    historyObjectCounter: number;
    canvas: HTMLCanvasElement;
    raf: number;
    previewPhone: CanvasShape | null;
    previewPhones: PreviewGeometry["phones"];
    previewImages: PreviewGeometry["images"];
    previewTextZones: TextZone[];
    activeObject: string;
    selectedText: "headline" | "subtitle" | null;
    pointerAction: any;
    canvasZoomMode: string;
    canvasZoomPercent: number;
    frameSpecs: Record<string, FrameSpec>;
    mockupCache: Record<string, MockupAssets>;
    serifFonts: Record<string, boolean>;
    workspaceHistoryButtons: Record<string, boolean>;
    createDevice: (copy?: Device) => Device;
    createBlankSlide: () => Slide;
    cloneDeviceForSlide: (source: Device) => Device;
    cloneSlide: (source: Slide) => Slide;
    cloneHistoryValue: (...args: any[]) => any;
    historySignature: (...args: any[]) => any;
    snapshotSlide: (slide: Slide) => Slide;
    snapshotWorkspace: () => WorkspaceSnapshot;
    slideHistory: (slide: Slide) => HistoryStacks<Slide>;
    recordSlideHistory: (slide: Slide, before: Slide) => boolean;
    recordWorkspaceHistory: (before: WorkspaceSnapshot) => boolean;
    restoreSlideSnapshot: (slide: Slide, snapshot: Slide) => void;
    refreshAfterHistory: (...args: any[]) => any;
    restoreWorkspaceSnapshot: (snapshot: WorkspaceSnapshot) => void;
    newestHistoryAction: (direction: 'undo' | 'redo') => HistoryAction | null;
    performHistory: (direction: 'undo' | 'redo') => void;
    beginSlideHistory: (slide?: Slide) => void;
    beginWorkspaceHistory: () => void;
    commitHistoryTransaction: () => void;
    beginInputHistory: () => void;
    commitInputHistory: () => void;
    activeDevice: () => Device;
    frameSpec: (kind: string) => FrameSpec;
    mockupAssets: (kind: string) => MockupAssets;
    deviceLabel: (...args: any[]) => any;
    activeSlideIndex: () => number;
    renderSlideThumbnail: (...args: any[]) => any;
    renderAllThumbnails: (...args: any[]) => any;
    switchSlide: (id: number) => void;
    rr: (c: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) => void;
    luminance: (hex: string) => number;
    textColor: (bg: string) => string;
    fontFamily: (name: string) => string;
    ensureFont: (name: string, weight: number) => Promise<FontFace[]>;
    ensureSelectedFonts: () => Promise<FontFace[][]>;
    colorWithAlpha: (hex: string, alpha: number) => string;
    mixHex: (a: string, b: string) => string;
    backgroundTextBase: () => string;
    drawBackground: (c: CanvasRenderingContext2D, p: Dimensions) => void;
    fitText: (c: CanvasRenderingContext2D, text: string, maxWidth: number, start: number, min: number, weight: number) => number;
    wrapText: (c: CanvasRenderingContext2D, text: string, maxWidth: number, maxLines: number) => string[];
    drawImageFitted: (c: CanvasRenderingContext2D, img: HTMLImageElement, x: number, y: number, w: number, h: number, device: Device) => void;
    drawPlaceholder: (c: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, dark: boolean) => void;
    drawPhone: (c: CanvasRenderingContext2D, p: Bounds, kind: string, device: Device) => void;
    applyPhoneState: (base: Bounds, p: Dimensions, device: Device) => CanvasShape;
    applyImageState: (base: Bounds, p: Dimensions, device: Device) => CanvasShape;
    drawImageLayer: (c: CanvasRenderingContext2D, p: CanvasShape, device: Device) => void;
    drawPhoneTransformed: (c: CanvasRenderingContext2D, p: CanvasShape, device: Device) => void;
    drawSelection: (c: CanvasRenderingContext2D, p: CanvasShape, output: Dimensions) => void;
    textZoneFor: (block: TextBlock, output: Dimensions) => TextZone;
    drawTextBlock: (c: CanvasRenderingContext2D, block: TextBlock, output: Dimensions, full: boolean, shift: Point) => TextZone;
    drawTextSelection: (c: CanvasRenderingContext2D, zone: TextZone, output: Dimensions) => void;
    deviceBaseFromReference: (base: Bounds, spec: FrameSpec) => Bounds;
    drawCanvas: (target: HTMLCanvasElement, full: boolean, dimensions?: Dimensions, slide?: Slide) => PreviewGeometry;
    fitPreviewCanvases: (...args: any[]) => any;
    renderPreviewFilmstrip: (...args: any[]) => any;
    render: () => void;
    showToast: (message: string) => void;
    clamp: (value: number, min: number, max: number) => number;
    pointerPoint: (e: PointerEvent | MouseEvent) => Point;
    textZoneAt: (point: Point) => TextZone | null;
    closeInlineEditor: (...args: any[]) => any;
    openInlineEditor: (...args: any[]) => any;
    pointInPhone: (point: Point, phone: CanvasShape) => Point;
    phoneContains: (point: Point, phone: CanvasShape) => boolean;
    phoneHitAt: (point: Point) => {
        id: number;
        phone: CanvasShape;
    } | null;
    imageHitAt: (point: Point) => {
        id: number;
        image: CanvasShape;
    } | null;
    handleAt: (point: Point, phone: CanvasShape) => ResizeHandle | null;
    rotationHandleAt: (point: Point, phone: CanvasShape) => boolean;
    textHandleAt: (point: Point, zone: TextZone) => ResizeHandle | null;
    textRotationHandleAt: (point: Point, zone: TextZone) => boolean;
    readFile: (file?: File) => Promise<void>;
    readPatternFile: (file?: File) => Promise<void>;
    moveActiveSlide: (...args: any[]) => any;
    arrangeCascade: (announce: boolean) => void;
    arrangeSideBySide: () => void;
    handlePointerMove: (e: PointerEvent) => void;
    endPointer: (e: PointerEvent) => void;
    wait: (ms: number) => Promise<void>;
    waitForImage: (image: HTMLImageElement | null) => Promise<void>;
    ensureExportFonts: (slide: Slide) => Promise<void>;
    waitForSlideAssets: (slide: Slide) => Promise<unknown[]>;
    canvasBlob: (canvas: HTMLCanvasElement) => Promise<Blob>;
    renderSlideBlob: (slide: Slide) => Promise<Blob>;
    downloadPng: (all: boolean) => Promise<void>;
    readStickerImage: (file: File) => Promise<HTMLImageElement>;
    readConfigImage: (file: File) => Promise<HTMLImageElement>;
    downloadBlob: (blob: Blob, name: string) => Promise<void>;
    setCanvasZoom: (...args: any[]) => any;
    currentCanvasZoomPercent: (...args: any[]) => any;
    disposeAssets?: () => void;
    disposeExports?: () => void;
    notify: () => void;
    disposed: boolean;
    toast: string;
    exporting: boolean;
    inline: InlineEdit | null;
    toastTimer: ReturnType<typeof setTimeout> | null;
    bind: (id: string, type: string, handler: (this: any, event: any) => void, options?: unknown) => void;
    listen: (target: EventTarget, type: string, handler: (this: any, event: any) => void, options?: AddEventListenerOptions) => void;
}
